
variables:
  ARTIFACT_NAME: cars-api-v$CI_PIPELINE_IID.jar
  APP_NAME: cars-api
stages:
  - build
  - test_stage
  - code_quality
  - J_unit_test
  - deploy_stage

build:
  stage: build
  image: openjdk:12-alpine
  script:
    - sed -i "s/CI_PIPELINE_IID/$CI_PIPELINE_IID/" ./src/main/resources/application.yml
    - sed -i "s/CI_COMMIT_SHORT_SHA/$CI_COMMIT_SHORT_SHA/" ./src/main/resources/application.yml
    - sed -i "s/CI_COMMIT_BRANCH/$CI_COMMIT_BRANCH/" ./src/main/resources/application.yml
   # these 3 Varibales appear postman info end point
    - ./gradlew build #Build command for java apps via gradle
    - mv ./build/libs/cars-api.jar ./build/libs/$ARTIFACT_NAME
      #Re-named artifact as we renamed artifact variable with env variable
      # earlier it it just cars-api.jar now it is cars-api-v$CI_PIPELINE_IID.jar
  artifacts:
      paths:
        - ./build/libs/


smoke test:
  stage: test_stage
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/$ARTIFACT_NAME & #Run the application and in background
    - sleep 25
    - curl http://localhost:5000/actuator/health | grep "UP"
    ## Calling end point to check if application up or not
    ## this url was obtained from postman application Health GET-baseurl
code_quality: #Checks code quality against best practices
  stage: code_quality
  image: openjdk:12-alpine
  script:
    - ./gradlew pmdMain pmdTest
  artifacts:
    when: always
    paths:
      - build/reports/pmd  #Save the reports here
Unit_Test:
  stage: J_unit_test
  image: openjdk:12-alpine
  script:
    - ./gradlew tests
  artifacts:
    when: always
    paths:
      - build/reports/tests  #HTML reports generated
    reports:
      junit: build/test-results/test #Reports are saved in j unit format


deploy:
    stage: deploy_stage
    image:
      name: banst/awscli
      entrypoint: [""]
    before_script:
      - apk --no-cache add curl
      - apk --no-cache add jq

  # this command we use extract info of production url from deploy stage in json format
    script:

      - aws configure set region us-east-1
      - aws s3 cp ./build/libs/$ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME
      - CNAME=$(aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name "cars-api-env" --version-label=$CI_PIPELINE_IID | jq '.CNAME' --raw-output)
      - sleep 45
      - curl http://$CNAME/actuator/health | grep "UP"
      - curl http://$CNAME/actuator/info | grep "$CI_PIPELINE_IID"
