
variables:
  ARTIFACT_NAME: cars-api-v$CI_PIPELINE_IID.jar
  APP_NAME: cars-api
stages:
  - build
  - test_stage
  - code_quality
  - J_unit_test
  - deploy_stage
  - API_Testing
  - publishing

build:
  stage: build
  image: openjdk:12-alpine
  script:
    - sed -i "s/CI_PIPELINE_IID/$CI_PIPELINE_IID/" ./src/main/resources/application.yml
    - sed -i "s/CI_COMMIT_SHORT_SHA/$CI_COMMIT_SHORT_SHA/" ./src/main/resources/application.yml
    - sed -i "s/CI_COMMIT_BRANCH/$CI_COMMIT_BRANCH/" ./src/main/resources/application.yml
    # these 3 Variables appear postman info end point
    - ./gradlew build #Build command for java apps via gradle
    - mv ./build/libs/cars-api.jar ./build/libs/$ARTIFACT_NAME
    #Re-named artifact as we renamed artifact variable with env variable
    # earlier it it just cars-api.jar now it is cars-api-v$CI_PIPELINE_IID.jar
  artifacts:
      paths:
         - ./build/libs/


smoke test:
  stage: test_stage
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/$ARTIFACT_NAME & #Run the application and in background
    - sleep 25
    - curl http://localhost:5000/actuator/health | grep "UP"
    ## Calling end point to check if application up or not
    ## this url was obtained from postman application Health GET-baseurl
code_quality: #Checks code quality against best practices
  stage: test_stage
  image: openjdk:12-alpine
  script:
    - ./gradlew pmdMain pmdTest
  artifacts:
    when: always
    paths:
      - build/reports/pmd  #Save the reports here
Unit_Test:
  stage: test_stage
  image: openjdk:12-alpine
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - ./build/reports/tests  #HTML reports generated
    reports:
      junit: ./build/test-results/test/*.xml #Reports are saved in j unit format
#######################



deploy:
    stage: deploy_stage
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    before_script:
      - yum install -y jq

  # this command we use extract info of production url from deploy stage in json format
    script:

      - aws configure set region us-east-1
      - aws s3 cp ./build/libs/$ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME
      - CNAME=$(aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name "cars-api-env" --version-label=$CI_PIPELINE_IID | jq '.CNAME' --raw-output)
      - sleep 45
      - curl http://$CNAME/actuator/health | grep "UP"
      - curl http://$CNAME/actuator/info | grep "$CI_PIPELINE_IID"
API_Testing:
  stage: API_Testing
  image:
    name: vdespa/newman
    entrypoint: [""]
  script:
    - newman --version
    - newman run "Cars API.postman_collection.json" --environment cars-api-env.postman_environment.json --reporters cli,htmlextra,junit --reporter-htmlextra-export "newman/report.html" --reporter-junit-export "newman/report.xml"
  artifacts:
    when: always
    paths:
      - newman/
    reports:
      junit: newman/report.xml
publishing:
  stage: publishing
  script:
    - mkdir public
    - mv newman/report.xml public/index.html
  artifacts:
    paths:
      - public
