stages:
  - build
  - test_stage
  - deploy_stage
build:
  stage: build
  image: openjdk:12-alpine
  script:

    - ./gradlew build #Build command for java apps via gradle
  artifacts:
    paths:
     - ./build/libs/
smoke test:
  stage: test_stage
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/cars-api.jar & #Run the application and in background
    - sleep 25
    - curl http://localhost:5000/actuator/health | grep "UP"
    ## Calling end point to check if application up or not
    ## this url was obtained from postman application Health GET-baseurl
deploy:
    stage: deploy_stage
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    script:
      - aws configure set region us-east-1
      - aws s3 cp ./build/libs/cars-api.jar s3://$S3_BUCKET/cars-api.jar