variables:
  ARTIFACT_NAME: cars-api-v$CI_PIPELINE_IID.jar
  APP_NAME: car-api
stages:
  - build
  - test_stage
  - deploy_stage
build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build #Build command for java apps via gradle
    -  mv ./build/libs/cars-api.jar ./build/libs/$ARTIFACT_NAME  #Re-named artifact as we renamed artifact variable with env variable
    # earlier it it just cars-api.jar now it is cars-api-v$CI_PIPELINE_IID.jar

  artifacts:
    paths:
     - ./build/libs/
smoke test:
  stage: test_stage
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/$ARTIFACT_NAME & #Run the application and in background
    - sleep 25
    - curl http://localhost:5000/actuator/health | grep "UP"
    ## Calling end point to check if application up or not
    ## this url was obtained from postman application Health GET-baseurl
deploy:
    stage: deploy_stage
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    script:
      - aws configure set region us-east-1
      - aws s3 cp ./build/libs/$ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME
      - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name "production" --version-label=$CI_PIPELINE_IID
